### ISSUE TITLE
Scenario Construction

### ISSUE THREAD

**Issue by Tonyprusac** [Tonyprusac/Deco3801-Ember#7]
Uh oh, I really need to do this pronto, but basically the structure of a 'Scenario' needs to be defined

Such Variables need to be defined and agreed upon

- Those starting financial variables

- Those targeted financial variables

- Negative/Positive Event trigger modifiers

- Starting inventory, customers and expenses

- Where these variables are stored in the game loop

**Comment by zstra7** [comment]
I've got a start to this in game.js, right now its just hardcoded but the data structure could easily be loaded in.
